M48
; DRILL file {KiCad (6.0.8)} date Thu Apr 20 14:40:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T14:40:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.0357Y-2.477
X6.2089Y-2.477
T2
X4.9805Y-4.3754
X5.8073Y-4.3754
T0
M30
